### ISSUE TITLE
Spacing before and after the meta data isn't consistent

### ISSUE THREAD

**Issue by setco-website** [praveenscience/hackfortomorrow-linktree#1]
In this screenshot:

![image](https://user-images.githubusercontent.com/48595752/146680833-97442e95-b26a-42c8-9321-32abc617c9d1.png)

You can see that the spaces aren't consistent. Can I please work on the spaces to be consistent?

Thanks.

**Comment by praveenscience** [comment]
Yea, cool, thanks for informing. You can start working on this. 😁
